import { createLocaleContent } from '../localized';

export const content = createLocaleContent({
  locale: 'ja', slug: 'coffee-grinder-dose-retention-calculator', title: 'コーヒーグラインダーの残留量計算機', description: 'グラインダーの残留量を測定し、投入量、廃棄量、1日の使用量、コストを計算します。', faqTitle: 'グラインダー残留量のよくある質問', bibliographyTitle: 'コーヒー粉砕の参考資料',
  ui: { controlTitle: '投入量プロファイルを作成', unitSystemLabel: '単位系', unitMetric: 'メートル法', unitImperial: 'ヤード・ポンド法', unitWeightMetric: 'g', unitWeightImperial: 'oz', presetTitle: 'ワークフローを選択', presetSingleDose: 'シングルドーズ', presetEspressoBar: 'エスプレッソバー', presetZeroPurge: '低廃棄', presetCustom: 'カスタム', targetDoseLabel: '目標抽出量', targetDoseHint: '抽出したいコーヒー量', trialInputLabel: 'テスト投入量', trialInputHint: '粉砕前に量る', trialOutputLabel: 'テスト回収量', trialOutputHint: '排出後に量る', purgeLabel: '1回あたりの意図的なパージ', purgeHint: '意図的に捨てるコーヒー', sessionsLabel: '1日の回数', sessionsHint: '日次見積もり用', costLabel: 'コーヒー価格（1kg）', costHint: '購入価格を入力', currencyLabel: '通貨', currencyHint: '参考レートで価格を換算', currencyRateNote: '1 EUR = {rate} {currency}', resultTitle: 'キャリブレーション結果', statusLow: '残留量は少なめ', statusModerate: '変動を確認', statusHigh: '残留量が多め', mismatchWarning: '回収量が投入量を超えています。風袋と容器を確認して再測定してください。', retentionLabel: '残留率', chargeDoseLabel: '投入量', deliveredLabel: '抽出側の量', wasteLabel: '1回の廃棄量', costPerSessionLabel: '1回のコスト', dailyWasteLabel: '1日の廃棄量', dailyCostLabel: '1日のコスト', visualTitle: 'コーヒーの行き先', visualLoaded: 'パージを含む総投入量', visualDelivered: '抽出', visualRetained: '残留', visualPurge: 'パージ', calibrationTitle: '自分の測定値を使う', calibrationText: '普段の豆、挽き目、容器、払い出し方で測定してください。清掃や挽き目変更後は再測定します。', actionTitle: '再現できる手順', actionText: '目標量に測定した残留量を足して投入し、パージは別に記録します。', stepMeasure: '{input} {unit}を投入して入力値を記録します。', stepCompare: '{output} {unit}を回収し、入力値と比較します。', stepLoad: '次回から約{charge} {unit}を投入します。', stepPurge: '{purge} {unit}のパージを捨てるか再利用します。', stepLog: '1回あたり約{waste} {unit}の廃棄を記録します。', copyResult: '結果をコピー', copiedText: 'コピーしました', resetText: 'リセット', copyTemplate: 'グラインダー残留量\n残留量: {retention} {unit}\n投入量: {charge} {unit}\n1回の廃棄量: {waste} {unit}\n1回のコスト: {cost}' },
  faq: [{ question: 'グラインダーの残留量とは何ですか？', answer: '投入した豆と回収した粉の差です。残った粉が次の投入で出て、再現性に影響することがあります。' }, { question: '残留量はどう測りますか？', answer: '粉砕前の豆と、排出が終わった後の粉を量ります。豆、挽き目、容器、手順を揃えてください。' }, { question: '投入量とは何ですか？', answer: '目標抽出量を得るために投入する豆の目安で、測定した残留量を加えた値です。' }, { question: 'この計算機でグラインダーを試験できますか？', answer: 'いいえ。入力した試験結果の推定です。焙煎、挽き目、湿度、清掃、排出方法で結果は変わります。' }, { question: '毎回パージすべきですか？', answer: '必ずしも必要ではありません。挽き目変更後の混入を減らせますが、廃棄量は増えます。' }, { question: '回収量が投入量より多いのはなぜですか？', answer: '風袋、容器、または計量手順が一致していない可能性があります。' }],
  howTo: [{ name: '校正用の投入を行う', text: '投入した豆と回収した粉を量ります。' }, { name: '2つの測定値を入力する', text: '入力と出力をgまたはozで入力します。' }, { name: '目標量を設定する', text: '抽出したい量を指定します。' }, { name: 'パージを追加する', text: '1回あたりのパージと1日の回数を入力します。' }, { name: '結果を使う', text: '残留率、投入量、廃棄、コストを確認し、必要なら再測定します。' }],
  editorial: { measureTitle: 'グラインダーの残留量を測る', measureOne: '量った投入量でも、グラインダーの出口では変化します。この計算機は前後の測定を実用的な投入量に変換します。', measureTwo: '残留量は焙煎、挽き目、湿度、静電気、清掃、排出口の払い方で変わります。', calculationTitle: '計算方法', calculationList: ['残留量は投入量から回収量を引いた値で、負にはしません。', '残留率は残留量を投入量で割ります。', '投入量は目標抽出量に残留量を足します。', '1回の廃棄量は残留量と意図的なパージの合計です。'], workflowTitle: 'コーヒーの流れを読む', workflowText: '図では抽出される量、残る量、意図的にパージする量を分けて表示します。', costTitle: '1日のコストを見積もる', costText: 'kg単価と1日の回数から計画用の概算を出します。こぼれ、調整、価格変動は含みません。', actionList: ['設定を変える前に通常の投入を測る。', '目盛りだけでなく出口の量を量る。', '残留とパージを別々に記録する。', '清掃や大きな設定変更の後に再測定する。'], limitsTitle: '計算機の限界', limitsText: '内部のデッドスペース、粒子交換、抽出品質を測定・保証するものではありません。', tipTitle: '複数回測定する', tipText: '1回の計量は一時点の結果です。条件を揃えて複数回行い、代表的な平均を使ってください。' },
});
