import { createLocaleContent } from '../localized';

export const content = createLocaleContent({
  locale: 'ko', slug: 'coffee-grinder-dose-retention-calculator', title: '커피 그라인더 잔류량 계산기', description: '그라인더 잔류량을 측정하고 투입량, 폐기량, 일일 사용량과 비용을 계산합니다.', faqTitle: '그라인더 잔류량 질문', bibliographyTitle: '커피 분쇄 참고 자료',
  ui: { controlTitle: '도즈 프로필 만들기', unitSystemLabel: '측정 단위', unitMetric: '미터법', unitImperial: '야드파운드법', unitWeightMetric: 'g', unitWeightImperial: 'oz', presetTitle: '작업 흐름 선택', presetSingleDose: '싱글 도즈', presetEspressoBar: '에스프레소 바', presetZeroPurge: '저폐기', presetCustom: '사용자 설정', targetDoseLabel: '목표 추출 도즈', targetDoseHint: '추출하고 싶은 커피 양', trialInputLabel: '테스트 투입량', trialInputHint: '분쇄 전에 측정', trialOutputLabel: '테스트 회수량', trialOutputHint: '배출 후 측정', purgeLabel: '세션당 의도적 퍼지', purgeHint: '일부러 버리는 커피', sessionsLabel: '하루 세션 수', sessionsHint: '일일 예상치용', costLabel: '커피 원두 가격（kg당）', costHint: '구매 가격 입력', currencyLabel: '통화', currencyHint: '참고 환율로 가격 변환', currencyRateNote: '1 EUR = {rate} {currency}', resultTitle: '캘리브레이션 결과', statusLow: '잔류량 낮음', statusModerate: '변동 확인', statusHigh: '잔류량 높음', mismatchWarning: '회수량이 투입량보다 큽니다. 영점과 용기를 확인하고 다시 측정하세요.', retentionLabel: '잔류율', chargeDoseLabel: '투입 도즈', deliveredLabel: '추출 도즈', wasteLabel: '세션당 폐기량', costPerSessionLabel: '세션당 비용', dailyWasteLabel: '일일 폐기량', dailyCostLabel: '일일 비용', visualTitle: '커피가 가는 곳', visualLoaded: '퍼지를 포함한 총 투입량', visualDelivered: '추출', visualRetained: '잔류', visualPurge: '퍼지', calibrationTitle: '직접 측정한 값 사용', calibrationText: '평소 사용하는 원두, 분쇄도, 용기와 배출 습관으로 테스트하세요. 청소나 분쇄도 변경 후 다시 측정합니다.', actionTitle: '반복 가능한 작업 흐름', actionText: '목표 도즈에 측정된 잔류량을 더해 투입하고 퍼지는 따로 기록하세요.', stepMeasure: '{input} {unit}을 투입하고 입력값을 기록합니다.', stepCompare: '{output} {unit}을 모아 입력값과 비교합니다.', stepLoad: '다음부터 약 {charge} {unit}을 투입합니다.', stepPurge: '계획한 {purge} {unit} 퍼지를 버리거나 재사용합니다.', stepLog: '세션당 약 {waste} {unit}의 폐기를 기록합니다.', copyResult: '결과 복사', copiedText: '복사됨', resetText: '초기화', copyTemplate: '그라인더 잔류량\n잔류량: {retention} {unit}\n투입 도즈: {charge} {unit}\n세션당 폐기: {waste} {unit}\n세션당 비용: {cost}' },
  faq: [{ question: '그라인더 잔류량이란 무엇인가요?', answer: '투입한 원두와 회수한 분쇄 커피의 차이입니다. 남은 커피가 다음 도즈에서 나와 반복성에 영향을 줄 수 있습니다.' }, { question: '잔류량은 어떻게 측정하나요?', answer: '분쇄 전 원두와 배출이 끝난 뒤의 분쇄 커피를 측정합니다. 원두, 분쇄도, 용기와 절차를 같게 하세요.' }, { question: '투입 도즈는 무엇인가요?', answer: '목표 추출량을 얻기 위해 넣을 원두의 양으로, 측정된 잔류량을 목표량에 더한 값입니다.' }, { question: '이 계산기가 그라인더를 테스트하나요?', answer: '아니요. 입력한 테스트의 추정치입니다. 로스팅, 분쇄도, 습도, 청소와 배출 방식에 따라 달라집니다.' }, { question: '항상 퍼지해야 하나요?', answer: '아닙니다. 분쇄도 변경 후 혼입을 줄일 수 있지만 폐기량은 늘어납니다.' }, { question: '회수량이 투입량보다 큰 이유는 무엇인가요?', answer: '영점, 용기 또는 측정 절차가 일치하지 않았을 가능성이 큽니다.' }],
  howTo: [{ name: '캘리브레이션 도즈 실행', text: '투입 원두와 회수한 분쇄 커피를 측정합니다.' }, { name: '두 측정값 입력', text: '입력과 출력을 g 또는 oz로 입력합니다.' }, { name: '목표량 설정', text: '원하는 추출량을 지정합니다.' }, { name: '퍼지 추가', text: '세션당 퍼지와 하루 세션 수를 입력합니다.' }, { name: '결과 적용', text: '잔류율, 투입량, 폐기와 비용을 확인하고 필요하면 반복합니다.' }],
  editorial: { measureTitle: '그라인더 잔류량 측정', measureOne: '측정한 도즈도 그라인더 출구에서 달라질 수 있습니다. 이 계산기는 전후 테스트를 실용적인 투입량으로 바꿉니다.', measureTwo: '잔류량은 로스팅, 분쇄도, 습도, 정전기, 청소와 배출구를 비우는 방법에 따라 달라집니다.', calculationTitle: '계산 방식', calculationList: ['잔류량은 투입량에서 회수량을 뺀 값이며 음수가 되지 않습니다.', '잔류율은 잔류량을 투입량으로 나눕니다.', '투입 도즈는 목표량에 잔류량을 더합니다.', '세션당 폐기는 잔류량과 의도적 퍼지의 합입니다.'], workflowTitle: '커피 흐름 읽기', workflowText: '시각화는 추출되는 커피, 남는 커피와 의도적으로 퍼지하는 커피를 나눠 보여줍니다.', costTitle: '일일 비용 추정', costText: 'kg당 가격과 하루 세션 수로 계획용 비용을 계산합니다. 흘림, 다이얼인과 가격 변동은 제외됩니다.', actionList: ['설정을 바꾸기 전에 평소 도즈를 측정하세요.', '눈금만 믿지 말고 출구의 양을 측정하세요.', '잔류와 퍼지를 따로 기록하세요.', '청소나 큰 설정 변경 후 반복하세요.'], limitsTitle: '계산기의 한계', limitsText: '내부 데드 스페이스, 입자 교환이나 추출 품질을 측정하거나 보증하지 않습니다.', tipTitle: '여러 번 테스트하세요', tipText: '한 번의 측정은 한 순간의 결과입니다. 같은 조건으로 여러 번 테스트하고 대표 평균을 사용하세요.' },
});
