import { createLocaleContent } from '../localized';

export const content = createLocaleContent({
  locale: 'zh', slug: 'coffee-grinder-dose-retention-calculator', title: '咖啡研磨机残留量计算器', description: '测量研磨机残留量，并计算投豆量、浪费量、每日用量和成本。', faqTitle: '研磨机残留量常见问题', bibliographyTitle: '咖啡研磨参考资料',
  ui: { controlTitle: '建立你的粉量档案', unitSystemLabel: '测量单位', unitMetric: '公制', unitImperial: '英制', unitWeightMetric: 'g', unitWeightImperial: 'oz', presetTitle: '选择工作流程', presetSingleDose: '单份粉量', presetEspressoBar: '咖啡吧', presetZeroPurge: '低浪费', presetCustom: '自定义', targetDoseLabel: '目标出粉量', targetDoseHint: '你想冲煮的咖啡量', trialInputLabel: '测试投豆量', trialInputHint: '研磨前称重', trialOutputLabel: '测试收粉量', trialOutputHint: '出粉后称重', purgeLabel: '每次有意排粉量', purgeHint: '主动丢弃的咖啡', sessionsLabel: '每天次数', sessionsHint: '用于每日估算', costLabel: '每公斤咖啡豆价格', costHint: '使用购买价格', currencyLabel: '货币', currencyHint: '使用参考系数换算价格', currencyRateNote: '1 EUR = {rate} {currency}', resultTitle: '你的校准结果', statusLow: '残留量低', statusModerate: '检查波动', statusHigh: '残留量高', mismatchWarning: '收粉量高于投豆量。请检查去皮并重复测试。', retentionLabel: '残留率', chargeDoseLabel: '投豆量', deliveredLabel: '出粉量', wasteLabel: '每次浪费', costPerSessionLabel: '每次成本', dailyWasteLabel: '每日浪费', dailyCostLabel: '每日成本', visualTitle: '咖啡去了哪里', visualLoaded: '含排粉的总投豆量', visualDelivered: '出粉', visualRetained: '残留', visualPurge: '排粉', calibrationTitle: '使用自己的测量值', calibrationText: '使用平时的咖啡豆、刻度、容器和清粉习惯测试。清洁或改变刻度后重新测量。', actionTitle: '可重复的流程', actionText: '目标出粉量加上测得的残留量就是投豆参考值，排粉要单独记录。', stepMeasure: '投入 {input} {unit} 咖啡豆并记录输入量。', stepCompare: '收集 {output} {unit} 并与输入量比较。', stepLoad: '以后每次投入约 {charge} {unit}。', stepPurge: '丢弃或重复利用计划中的 {purge} {unit} 排粉。', stepLog: '记录每次约 {waste} {unit} 的浪费。', copyResult: '复制结果', copiedText: '已复制', resetText: '重置', copyTemplate: '研磨机残留量\n残留量：{retention} {unit}\n投豆量：{charge} {unit}\n每次浪费：{waste} {unit}\n每次成本：{cost}' },
  faq: [{ question: '什么是研磨机残留量？', answer: '它是投入的咖啡豆与收集到的咖啡粉之间的差值。残留粉可能在下一次出粉并影响一致性。' }, { question: '如何测量残留量？', answer: '研磨前称豆，出粉结束后称粉，并保持咖啡豆、刻度、容器和流程一致。' }, { question: '投豆量是什么意思？', answer: '这是为了得到目标出粉量而建议投入的咖啡豆量，包含测得的残留量。' }, { question: '这个计算器能测试研磨机吗？', answer: '不能。它只根据你的测试进行估算。烘焙、刻度、湿度、清洁和清空出口的方式都会影响结果。' }, { question: '需要每次都排粉吗？', answer: '不一定。改变刻度后排粉可以减少咖啡串味，但会增加浪费，应该单独记录。' }, { question: '为什么收粉量大于投豆量？', answer: '通常是去皮、容器或称重流程不一致造成的。' }],
  howTo: [{ name: '进行校准测试', text: '称量投入的咖啡豆和收集到的咖啡粉。' }, { name: '输入两项测量', text: '用克或盎司输入投豆量和收粉量。' }, { name: '设置目标量', text: '输入想要冲煮的咖啡量。' }, { name: '加入排粉量', text: '填写每次排粉量和每天次数。' }, { name: '应用结果', text: '查看残留、投豆、浪费和成本，必要时重复测试。' }],
  editorial: { measureTitle: '测量研磨机残留量', measureOne: '即使投豆量已经称过，研磨机出口的实际出粉仍可能变化。这个计算器把前后称重测试转化为可执行的投豆量。', measureTwo: '残留量会受到烘焙、研磨刻度、湿度、静电、清洁和清空出口方式的影响。', calculationTitle: '计算方式', calculationList: ['残留量等于投豆量减去收粉量，不会出现负数。', '残留率是残留质量除以投豆量。', '投豆量是目标出粉量加测得的残留量。', '每次浪费等于残留量加有意排粉量。'], workflowTitle: '阅读咖啡流向', workflowText: '图示区分进入咖啡杯的咖啡、留在研磨机中的咖啡以及主动排出的咖啡。', costTitle: '估算每日成本', costText: '每公斤价格和每天次数可以给出规划用估算，不包含洒落、调参和价格变化。', actionList: ['改变刻度前测量一次普通剂量。', '称量出粉，不要只相信刻度盘。', '分别记录残留和排粉。', '清洁或大幅调整后重新测试。'], limitsTitle: '计算器的限制', limitsText: '它不能测量内部死角、颗粒交换，也不能保证萃取质量。', tipTitle: '重复测试', tipText: '一次称重只是一个瞬间。请在相同条件下多测几次，并使用有代表性的平均值。' },
});
